[paths]
unformatted = "/content/drive/MyDrive/tick/"
unformatted_tick = "/content/drive/MyDrive/tick/"
formatted = "/content/formatted/"
intraday = "/content/intraday/"

[yf_tickers]
GC_F = "GC=F"
ES_F = "ES=F"
NG_F = "NG=F"

[resampler]
file_name_format = "_"

[baskets]
Energy = [ "HO_F", "CL_F",]
Financials = [ "ES_F", "ZB_F",]
Agriculturals = [ "LE_F",]
PMs = [ "GC_F"]
Agris = [ "LE_F"]

[aliases.unformatted]
GC_F = "GC_F.csv"
ES_F = "ES_F.csv"
NG_F = "NG_F.csv"
CL_F = "CL_F.csv"
ZB_F = "ZB_F.csv"
LE_F = "LE_F.csv"

[aliases.formatted]
GC_F = "GC_F_5min"
ES_F = "ES_F_5min"
NG_F = "NG_F_5min"
CL_F = "CL_F_5min"
ZB_F = "ZB_F_5min"
LE_F = "LE_F_5min"

[aliases.intraday]
CL_F = "CL_5s"
GC_F = "GC_5s"
LE_F = "LE_5s"
ZC_F = "ZC_5s"
NG_F = "NG_5s"
